import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <section>
      <Head>
        <title>Employee Management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-xl md:text-5xl text-center font-bold py-10">
          Employee Management
        </h1>
        <div className="container mx-auto flex justify-between py-5 border-b">
          <div className="left flex gap-3">
            <button className="flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-gray-50 hover:border-dindigo-500 hover:text-gray-800">Add Employee</button>
          </div>
        </div>
      </main>
    </section>
  );
};

export default Home;
